### PR TITLE
V3: fix correct type for variables

### PR DESCRIPTION
**Pull request by tuanddd**
## What this PR does
- [x] Add correct optional type for `Variables`
- [x] Handle `undefined` case

### CODE REVIEW

**Comment by sampotts** [comment]
Should this issue with the empty search be fixed?
https://deploy-preview-263--sajari-react-sdk-v3.netlify.app/search-ui/filter

image

**Comment by tuanddd** [comment]
> Should this issue with the empty search be fixed?
> https://deploy-preview-263--sajari-react-sdk-v3.netlify.app/search-ui/filter
> 
> image

I think it's related to the `filter` field not being set correctly, which has been fixed in #255

**Comment by sampotts** [comment]
Hey @tuanddd, could you resolve the conflict on this? Cheers

**Comment by tuanddd** [comment]
Ah yeah will do

**Review by sampotts — APPROVED** [review]

**Pull request merged**
